# This workflow mirrors the code to the wknd.site repository
name: Deploy to WKND.site Production
env:
  # Target repository
  TARGET_REPO: ${{ secrets.WKND_REPOSITORY }}
  TARGET_BRANCH_DEV: ${{ secrets.WKND_BRANCH_DEV }}
  TARGET_BRANCH_PROD: ${{ secrets.WKND_BRANCH_PROD }}
  USER_EMAIL: ${{ secrets.WKND_USER_EMAIL }}
  USER_NAME: ${{ secrets.WKND_USER_NAME }}
  USER_PWD: ${{ secrets.WKND_PASSWORD }}

# Only run on a push to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
 deploy:
    name: Deploy to Stage
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['16']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
        with:
          os: ${{ matrix.os }}
          version: 9.x.x
      - name: Setup cm-pipeline-execution-action
        uses: adobe/aio-cloudmanager-create-execution-action@v1.0.5
        with:
          os: ${{ matrix.os }}
          version: 9.x.x
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Create Execution
          uses: adobe/aio-cloudmanager-create-execution-action@v1.0.5
          with:
            CLIENTID: abba070b2452468c8ab2021093367300
            CLIENTSECRET: $p8e-3I2TdMDOz0f4nmTK9UxncXJhvNguaHKh
            TECHNICALACCOUNTID: D0C03F986565DCB60A495C04@techacct.adobe.com
            IMSORGID: 213C58BF5BC725F60A495C9C@AdobeOrg
            KEY: -----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjaY52O7Q7Wb+bMrZHnZxRHVOB
6Fz7PTBNcbJJXVBdg7g3p5ZZW2Nsuej/zuiznPsm9jPZANZhcZ8giXIivX6W7Z3w2F5XTUjJ0kuk
gr6OxYXfGdYOU5H+bFivJn0uXY9cpisW0CeV817SKQiG2NO96sZ9yiCiCXZ6s6UNCvlEq7bkAWsj
mNNGQEiTyhVdAOB8QXAxq3omAMvgbeNPUmZnswynZN7ETTRaNRv95Rn5S0Iw8tW5dGppKATSdctb
PspZaebw/Ov1YDuwRuvZdUlQ3k2gBEMXyl78ghU92Xo/B812OAgx9AZRlJTiQDH7seG/KIzuQYR2
ghHUOorZF65/AgMBAAECggEAC0hlgrpalmJ6/U9CEK3MNjmNI4IUsXAnHqHECpa7zskidg1HL0JF
GiO397mkjYpAOQ90wv3wz2eV8hwrWkS1MdyUNCXsVaDLbsvrVx+D4r22oZHaGsEgam22rdk9eW8S
T/ZVMU0L/qmAGYilwxHDhPBp5hOHr0hx+sTel4jzbw9DysFImkUS1o3WRpKVqDfEDRSJ3MM+8BuV
nX7Q9FZQ7lVic9rC84LbKQOPdLTsjAUzJOduxK+swpU/58s85vIodqGrslJq5Rk+2+OeV96jdqyk
4imnhKvyy4szPLt0wc/M9GyVNY2Antcw3xZWznfKX7NH2oXugCVmNOUvFhXRSQKBgQDdk0gG4m8d
4jbQoTQOm4zYYpqEt1btem5CLnoSWD9NMkpMaREs01lmcHLFl8Ie/+pA/YgbqBQbQijTYJS/F/fo
f47FNEMo/bhGUW2MeVqEXkWEZLRw8BWbGCAy3a01hdgDiB5Sx1eaEeKB+EQX5o6+yRJzHU5gjpkS
2K7PQW1BdQKBgQC8zPUrtIltOQCKFboNKOd8MzC9IFBhQesJRCxdi1dea06Rq0cIip6tncuW0oMW
E5ZYYFxulzTkJ7tVJBS3ut9FYKpnCp9UOMP3Hd/dkND6Kqf5Gs68Wv4sMBRVOdUsJ6Uxu1KWPHZl
GdudrPxHEf3rYJRJk4WcSs7lKv1kZVHdowKBgCB4aOG5ZRc4A1hnhz1sxiMfsA0q4O5ENsw0C2eM
zxn8+K5h50ZuYneEmw0hxCzOzAFiJgQHiYrFEz6GtMWcOZQ0vTNhCUaEh/CmFiuzzPQA7KcOKvMx
+7iSvIU3vx5M0u8Rj4AJ/mhxnoP1YeUuwFRtGusLrGSyAPSmFFgC+oPRAoGANE9dRoS45ug6PAgV
Cnxg1sqgIGaJnsjSxDh9SlXHGUQF+tpHzhgKKvRjaiBdbYpzx3y7X3DJmMVhZA+hJd7C6cgErpQE
3SL1OMywMAVlwUp8S8qfqRRVBA02NP7XD2rUnFjYYwPRkeV+McuyAkb74XFa5J/ZDxqzBE/K8TwZ
WJ0CgYEAyuVd9BD5tuMG43xCKxa6rE36Lk1EhQGM54B9I1qgy7to0dERbKKVq70hmNs9hKGQaLaN
S1xHeQAT0HyN7J+oB+O8yaVGznZRrVj9YTUVenOV8jM9MrPQ0XGZW8fCoasA83fuaTNQB74c968L
R7UoLiS/3+EgGyzYTIO1xrOyNak=
-----END PRIVATE KEY-----
            PIPELINEID: 12150506
            PROGRAMID: 89809
