name: Hello World with Auth

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate
      uses: adobe/aio-cloudmanager-create-execution-action@v1.0.5
      with:
        command: auth
        CLIENTID: d7b1dc0fe3124da39dd1c1db61522cac
        CLIENTSECRET: p8e-aM_xKhjXeNk21y7ZT7U3oZVZuw9ua70X
        TECHNICALACCOUNTID: 22C530316568AD3C0A495C50@techacct.adobe.com
        IMSORGID: 213C58BF5BC725F60A495C9C@AdobeOrg
        SCOPES: 'ent_cloudmgr_sdk'
        KEY: ${{ secrets.KEY_STAGE }}
        PIPELINEID: 12150506
        PROGRAMID: 89809

    - name: Print Hello World
      run: echo "Hello, World!"
