name: Hello World with Auth

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate
      uses: adobe/aio-apps-action@2.0.1
      with:
        command: auth
        CLIENTID: abba070b2452468c8ab2021093367300
        CLIENTSECRET: p8e-3I2TdMDOz0f4nmTK9UxncXJhvNguaHKh
        TECHNICALACCOUNTID: D0C03F986565DCB60A495C04@techacct.adobe.com
        IMSORGID: 213C58BF5BC725F60A495C9C@AdobeOrg
        SCOPES: 'ent_cloudmgr_sdk'
        KEY: ${{ secrets.KEY_STAGE }}

    - name: Print Hello World
      run: echo "Hello, World!"
